### ISSUE TITLE
这套固件似乎没办法正常连接ssh

### ISSUE THREAD

**Issue by Anivie** [sagehou/360T7-ImmortalWrt#3]
请问是我的问题还是固件有其他设置？

**Comment by sagehou** [comment]
系统-->管理权-->SSH访问 有相关设置，我这边使用是正常的。

**Comment by Anivie** [comment]
> 系统-->管理权-->SSH访问 有相关设置，我这边使用是正常的。

都改了一遍也没连上去，只要输入密码就直接切断连接，不过也用不到就不管了
